VAGRANT_DISABLE_SMBMFSYMLINKS=1

Vagrant.configure("2") do |config|
    #config.vm.box = "hashicorp/bionic64"
    config.vm.box = "centos/7"
    #config.vm.box = "ubuntu/trusty64"
    config.vm.hostname = "client1"
    config.vm.network "private_network", ip: "10.1.1.3"
    #config.vm.network "forwarded_port", guest: 3000, host:3000
    config.vm.synced_folder ".", "/vagrant", type: "smb",
        smb_host: "10.1.1.1",
        smb_username: "vagrant", 
        smb_password: "vagrant",
        mount_options: ["username=vagrant","password=vagrant"]
    config.vm.provision "shell", path: "provision.sh"
    config.vm.provider 'virtualbox' do |v|
        v.memory = 1024
        #v.disk "disk", size: "30GB", name: "data"
    end
end