Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "sonarqube"
  #config.vm.network 'forwarded_port', guest: 9000, host:9000, hostip: '127.0.0.1 
  config.vm.network 'forwarded_port', guest: 9000, host:9000
  config.vm.network "private_network", ip: "10.2.1.10"
  config.vm.provision 'shell', path: 'provision.sh'
  config.vm.provider 'virtualbox' do |v|
    v.memory =1024
  end
end
