Vagrant.configure("2") do |config|
    config.vm.box = 'centos/7'
    config.vm.hostname = 'manager'
    config.vm.define = 'manager'
    config.vm.network 'private_network', ip:'10.3.1.2'
    config.vm.provision 'shell', path: 'provision.sh'
    config.vm.provider 'virtualbox' do |v|
        v.memory = 2048
    end
end