---
- name: configurar servidor de base de dados
  hosts: db01

  user: vagrant
  become: yes
  vars_files:
    - vars/main.yml
  vars: 
    - dbname: "db01"
    - dbusername: "root"
    - dbpassword: "dbpass"
  roles:
    - configuracao-dafault-so
    - role: geerlingguy.mysql
