---
- name: atualização do hosts nos servidores
  hosts: all

  user: vagrant
  become: yes

  tasks:
    - name: configurar hosts lab ansible
      lineinfile:
        dest: /etc/hosts
        state: present
        line: "{{item}}"
      with_items:
        - 10.1.1.2 control-node
        - 10.1.1.3 app01
        - 10.1.1.4 db01
        - 10.1.1.5 docker01
        - 10.2.1.10 sonar
        - 10.2.1.11 jenkins
        - 10.3.1.2 manager