---
- name: instalar o sonar-scanner no Jenkins Server Master
  hosts: jenkins

  user: vagrant
  become: yes
  
  tasks:
    - name: instalacao do unzip
      yum:
        name: unzip
        state: latest
    - name: Donwload do sonar-scanner 
      get_url:
        url: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
        dest: /opt/sonar-scanner-cli-4.6.2.2472-linux.zip
    - name: Unzip do pacote sonar-scanner
      ansible.builtin.unarchive:
        src: /opt/sonar-scanner-cli-4.6.2.2472-linux.zip
        dest: /opt/
        remote_src: yes
    - name: stat sonar-scanner
      ansible.builtin.stat: 
          path=/opt/sonar-scanner
      register: sonarstat
    - name: stat da pasta /opt/sonar-scanner-cli-4.6.2.2472-linux
      ansible.builtin.stat: 
          path=/opt/sonar-scanner-cli-4.6.2.2472-linux
      register: sonarscannerdir
    - name: Alterar o nome da pasta sonar
      command: 
        mv /opt/sonar-scanner-cli-4.6.2.2472-linux /opt/sonar-scanner
    - name: Instalar o repositorio de nodejs
      command: curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -
    - name: Fazer o refresh do yum 
      command: sudo yum clean all && sudo yum makecache fast
    - name: instalacao do gcc
      yum:
        name: gcc-c++
        state: latest
    - name: Instalação do make
      yum:
        name: make
        state: latest
    - name: Change permission da pasta sonar-scanner
      file:
        path: /opt/sonar-scanner
        state: directory
        owner: jenkins
        group: jenkins
        mode: a+x
      when: sonarstat.stat.isdir is not defined
    - name: apagar o ficheiro sonar-scanner-cli-4.6.2.2472-linux.zip
      ansible.builtin.file:
        path: /opt/sonar-scanner-cli-4.6.2.2472-linux.zip
        state: absent
    - name: Recursively remove directory
      ansible.builtin.file:
        path: /opt/sonar-scanner-4.6.2.2472-linux
        state: absent
      when: sonarscannerdir.stat
    - name: Alterar o profile 
      lineinfile:
        dest: /etc/profile
        state: present
        line: "{{item}}"
      with_items:
        - export PATH=$PATH:/opt/sonar-scanner/bi
      when: sonarstat.stat.isdir is not defined
  roles:
    - configuracao-dafault-so



    
