
Vagrant.configure("2") do |config|
  # vamos fazer um echo apenas para sabemros que vai iniciar a criação do cluster de swarm
    config.vm.provision "shell", inline: "echo config docker swarm cluster"
    config.vm.define "manager" do |manager|
      manager.vm.box = "centos/7"
      manager.vm.hostname= "manager"
      manager.vm.provision "shell", path: "provision.sh"
      #criação de uma rede privada para o cluster de swarm
      manager.vm.network "private_network", ip: "10.2.1.2"
      #Vamos fazer um forwarded por para testar
      manager.vm.network "forwarded_port", guest: 80, host:8090
    end
    config.vm.define "worker1" do |worker1|
      worker1.vm.box = "centos/7"
      worker1.vm.hostname= "worker1"
      worker1.vm.provision "shell", path: "provision.sh"
      worker1.vm.network "private_network", ip: "10.2.1.3"
    end
    #O worker 2 do cluster de docker
     config.vm.define "worker2" do |worker2|
      worker2.vm.box = "centos/7"
      worker2.vm.hostname= "worker2"
      worker2.vm.provision "shell", path: "provision.sh"
      worker2.vm.network "private_network", ip: "10.2.1.4"
    end
end
