Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = "prometheus"
    config.vm.define "promotheus"
    config.vm.network 'private_network', ip: "10.3.1.4"
    config.vm.network 'forwarded_port', guest: 9090, host: 9090
    config.vm.provision "shell", path: "provision.sh"
    config.vm.provider 'virtualbox' do |v|
        v.memory = 2048
    end
end