VAGRANT_DISABLE_SMBMFSYMLINKS=1
Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  #config.vm.box = "centos/7"
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: "10.1.1.2"
  config.vm.synced_folder ".", "/vagrant", type: "smb",
      smb_host: "10.1.1.2"
      #smb_username: "vagrant", 
      #smb_password: "vagrant",
      #mount_options: ["username=vagrant","password=vagrant"]
  config.vm.provision "shell", path: "provision.sh"
end
