
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "docker01"
  config.vm.network "private_network", ip: "10.1.1.5"
  config.vm.provision "shell", path: "provision.sh"
  
end
