---
- name: Add or update user password
  hosts: client1

  tasks:
  - name: change "George" password
    user:
     name: george
     update_password: always
     password: "{{ newpassword|password_hash('sha512') }}"
