---
- name: Install packages thru loop
  hosts: client1
  vars:
    packages: [ftp,telnet, htop]

  tasks:
  - name: Install packages
    yum:
       name: '{{ item }}'
       state: present
    with_items: '{{ packages }}'