---
- name: Create users thru loop
  hosts: client1
  
  tasks:
  - name: Create users
    user:
     name: "{{ item }}"
     home: /home/{{ item }}
     shell: /bin/bash
    loop:
     - nmmelo
     - lpsa
     - pcardoso
