Vagrant.configure("2") do |config|
    config.vm.box = 'centos/7'
    config.vm.hostname = 'jenkins'
    config.vm.network 'forwarded_port', guest: 8080, host: 8080, hostip: '127.0.0.1'
    config.vm.network 'forwarded_port', guest: 8091, host: 8091, hostip: '127.0.0.1'
    config.vm.network 'forwarded_port', guest: 8123, host: 8123, hostip: '127.0.0.1'
    config.vm.network "private_network", ip: "10.2.1.11"
    config.vm.provision 'shell', path: 'provision.sh'
    config.vm.provider 'virtualbox' do |v| 
        v.memory =4096
    end
    config.vm.define "jenkins"
end